### ISSUE TITLE
Non-Linear Analysis

### ISSUE THREAD

**Issue by ajos6183** [VasilisMerevis/FiniteElementsProject#4]
Hi Vasilis,

I downloaded your code and i tried running the file "WriteLines2.txt". However, i am finding that the non-linear analysis is not converging and that it stops at the 1000th iteration which is the iteration limit.

Do you know why this is the case?

Thanks,
Anthony

**Comment by VasilisMerevis** [comment]
Hi Anthony.

Did you check test2 branch?

**Comment by ajos6183** [comment]
Thanks, i had a look at it now but still i am seeing that the solution is not converging and that the 1000 iteration limit is reached in each of the load steps.

Was there any theoretical reference that you used for writing this that you are able to share with me?
This would be very helpful for me as I am writing a non-linear analysis engine for 3D beams.

**Comment by VasilisMerevis** [comment]
Strange. I have just checked it. Using file WriteLines2NLCantilever seems to converge.
You could also try my FEC repository or MSOLVE. The last one is a collaborative effort.
Keep in mind though, that I  have used a **2D** co-rotational formulation for beams. You mentioned that you are interested in 3D beams (with geometrical non linearity I presume).
For references:
Papers: L. L. Yaw, J. M. Battini, T. N. Le, J. L. Meek (all of them referring to beam corotational formulation)
Books: Crisfield, Krenk (I used the first one, but I suggest the second one since it focuses on 3D corotational beams)

**Comment by ajos6183** [comment]
Thanks Vasilis, The FEC repository seems to work great for me and it converges very fast for the 2D example i tested! Maybe i was doing something wrong before.

I am interested in a geometrically non-linear 3D theory to analyse structural engineering problems. The deformations could be large but the strains are typically small. I was trying to avoid a 3D co-rotational formulation because of its complexity (for me) and because i didn't want to pick up any type of instability other than axial buckling effects. So i was thinking about using the Euler-Bernoulli theory and then adding a geometric stiffness matrix such as the one on page 257 of this book [http://digitalcommons.bucknell.edu/books/7/].

Do you think this is a feasible solution or am i on the wrong path?

**Comment by VasilisMerevis** [comment]
I am not familiar with this book so I haven't used its approach.  It does seem more straight forward than co-rotational formulation, so I guess you won't waste much time in implementation. So you can't go that wrong there.

**Comment by ajos6183** [comment]
OK, thanks for your help. It is much appreciated!
